spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5436/catalog
    username: catalog_user
    password: catalog_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
            - db