services:

  # =====================================================
  # Kafka
  # =====================================================

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"

    environment:
      # KRaft mode - no ZooKeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Internal Docker communication
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092

      # What clients should use to connect
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Local development
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Topics
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      # Local baseline
      KAFKA_NUM_PARTITIONS: 3

    networks:
      - event-driven-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  # =====================================================
  # Orders PostgreSQL
  # =====================================================

  orders-db:
    image: postgres:16
    container_name: orders-db

    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password

    ports:
      - "5433:5432"

    volumes:
      - orders-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - event-driven-network


  # =====================================================
  # Inventory PostgreSQL
  # =====================================================

  inventory-db:
    image: postgres:16
    container_name: inventory-db

    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password

    ports:
      - "5434:5432"

    volumes:
      - inventory-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - event-driven-network


  # =====================================================
  # Notifications PostgreSQL
  # =====================================================

  notifications-db:
    image: postgres:16
    container_name: notifications-db

    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: notifications_password

    ports:
      - "5435:5432"

    volumes:
      - notifications-db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifications_user -d notifications"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - event-driven-network


  # =====================================================
  # Catalog PostgreSQL
  # =====================================================
  catalog-db:
    image: postgres:16
    container_name: catalog-db
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
    ports:
      - "5436:5432"
    volumes:
      - catalog-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalog_user -d catalog" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-driven-network

    # =====================================================
    # Monitoring
    # =====================================================
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:9090/-/healthy || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - event-driven-network

    restart: unless-stopped

  # ==============================================================
  # Grafana
  # ==============================================================
  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:3000/api/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    depends_on:
      prometheus:
        condition: service_healthy

    networks:
      - event-driven-network

    restart: unless-stopped


# =====================================================
# Volumes
# =====================================================

volumes:
  orders-db-data:
  inventory-db-data:
  notifications-db-data:
  catalog-data:
  prometheus-data:
  grafana-data:


# =====================================================
# Network
# =====================================================

networks:
  event-driven-network:
    driver: bridge